// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shared-entity/proto/storage/v1/storage.proto

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UploadResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type UploadMultipleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileUpload          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMultipleRequest) Reset() {
	*x = UploadMultipleRequest{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMultipleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMultipleRequest) ProtoMessage() {}

func (x *UploadMultipleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMultipleRequest.ProtoReflect.Descriptor instead.
func (*UploadMultipleRequest) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMultipleRequest) GetFiles() []*FileUpload {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUpload) Reset() {
	*x = FileUpload{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpload) ProtoMessage() {}

func (x *FileUpload) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpload.ProtoReflect.Descriptor instead.
func (*FileUpload) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *FileUpload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileUpload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUpload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadMultipleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*UploadResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMultipleResponse) Reset() {
	*x = UploadMultipleResponse{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMultipleResponse) ProtoMessage() {}

func (x *UploadMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMultipleResponse.ProtoReflect.Descriptor instead.
func (*UploadMultipleResponse) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *UploadMultipleResponse) GetResults() []*UploadResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteByURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByURLRequest) Reset() {
	*x = DeleteByURLRequest{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByURLRequest) ProtoMessage() {}

func (x *DeleteByURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByURLRequest.ProtoReflect.Descriptor instead.
func (*DeleteByURLRequest) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteByURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadArchiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectPath    string                 `protobuf:"bytes,1,opt,name=object_path,json=objectPath,proto3" json:"object_path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArchiveRequest) Reset() {
	*x = UploadArchiveRequest{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArchiveRequest) ProtoMessage() {}

func (x *UploadArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArchiveRequest.ProtoReflect.Descriptor instead.
func (*UploadArchiveRequest) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *UploadArchiveRequest) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

func (x *UploadArchiveRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArchiveResponse) Reset() {
	*x = UploadArchiveResponse{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArchiveResponse) ProtoMessage() {}

func (x *UploadArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArchiveResponse.ProtoReflect.Descriptor instead.
func (*UploadArchiveResponse) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{9}
}

func (x *UploadArchiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DownloadArchiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectPath    string                 `protobuf:"bytes,1,opt,name=object_path,json=objectPath,proto3" json:"object_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArchiveRequest) Reset() {
	*x = DownloadArchiveRequest{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArchiveRequest) ProtoMessage() {}

func (x *DownloadArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArchiveRequest.ProtoReflect.Descriptor instead.
func (*DownloadArchiveRequest) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadArchiveRequest) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

type DownloadArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArchiveResponse) Reset() {
	*x = DownloadArchiveResponse{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArchiveResponse) ProtoMessage() {}

func (x *DownloadArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArchiveResponse.ProtoReflect.Descriptor instead.
func (*DownloadArchiveResponse) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadArchiveResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPresignedURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpirySeconds int64                  `protobuf:"varint,2,opt,name=expiry_seconds,json=expirySeconds,proto3" json:"expiry_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedURLRequest) Reset() {
	*x = GetPresignedURLRequest{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedURLRequest) ProtoMessage() {}

func (x *GetPresignedURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedURLRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedURLRequest) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{12}
}

func (x *GetPresignedURLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetPresignedURLRequest) GetExpirySeconds() int64 {
	if x != nil {
		return x.ExpirySeconds
	}
	return 0
}

type GetPresignedURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedURLResponse) Reset() {
	*x = GetPresignedURLResponse{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedURLResponse) ProtoMessage() {}

func (x *GetPresignedURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedURLResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedURLResponse) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{13}
}

func (x *GetPresignedURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetPresignedUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentLength int64                  `protobuf:"varint,3,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Sha256Hash    string                 `protobuf:"bytes,4,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"` // Checksum for deduplication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUploadURLRequest) Reset() {
	*x = GetPresignedUploadURLRequest{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUploadURLRequest) ProtoMessage() {}

func (x *GetPresignedUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{14}
}

func (x *GetPresignedUploadURLRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetPresignedUploadURLRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetPresignedUploadURLRequest) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *GetPresignedUploadURLRequest) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

type GetPresignedUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`        // Presigned URL to PUT data to (empty if is_duplicate is true)
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`              // Public/Download URL
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                                     // Object storage key
	IsDuplicate   bool                   `protobuf:"varint,4,opt,name=is_duplicate,json=isDuplicate,proto3" json:"is_duplicate,omitempty"` // True if file content already exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUploadURLResponse) Reset() {
	*x = GetPresignedUploadURLResponse{}
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUploadURLResponse) ProtoMessage() {}

func (x *GetPresignedUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_entity_proto_storage_v1_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP(), []int{15}
}

func (x *GetPresignedUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetPresignedUploadURLResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *GetPresignedUploadURLResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetPresignedUploadURLResponse) GetIsDuplicate() bool {
	if x != nil {
		return x.IsDuplicate
	}
	return false
}

var File_shared_entity_proto_storage_v1_storage_proto protoreflect.FileDescriptor

const file_shared_entity_proto_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	",shared-entity/proto/storage/v1/storage.proto\x12\n" +
	"storage.v1\"b\n" +
	"\rUploadRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"y\n" +
	"\x0eUploadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\"E\n" +
	"\x15UploadMultipleRequest\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.storage.v1.FileUploadR\x05files\"_\n" +
	"\n" +
	"FileUpload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"N\n" +
	"\x16UploadMultipleResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.storage.v1.UploadResponseR\aresults\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"&\n" +
	"\x12DeleteByURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x14UploadArchiveRequest\x12\x1f\n" +
	"\vobject_path\x18\x01 \x01(\tR\n" +
	"objectPath\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"1\n" +
	"\x15UploadArchiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x16DownloadArchiveRequest\x12\x1f\n" +
	"\vobject_path\x18\x01 \x01(\tR\n" +
	"objectPath\"-\n" +
	"\x17DownloadArchiveResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"Q\n" +
	"\x16GetPresignedURLRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x0eexpiry_seconds\x18\x02 \x01(\x03R\rexpirySeconds\"+\n" +
	"\x17GetPresignedURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xa5\x01\n" +
	"\x1cGetPresignedUploadURLRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12%\n" +
	"\x0econtent_length\x18\x03 \x01(\x03R\rcontentLength\x12\x1f\n" +
	"\vsha256_hash\x18\x04 \x01(\tR\n" +
	"sha256Hash\"\x8e\x01\n" +
	"\x1dGetPresignedUploadURLResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12!\n" +
	"\fis_duplicate\x18\x04 \x01(\bR\visDuplicate2\xb2\x05\n" +
	"\x0eStorageService\x12?\n" +
	"\x06Upload\x12\x19.storage.v1.UploadRequest\x1a\x1a.storage.v1.UploadResponse\x12W\n" +
	"\x0eUploadMultiple\x12!.storage.v1.UploadMultipleRequest\x1a\".storage.v1.UploadMultipleResponse\x12?\n" +
	"\x06Delete\x12\x19.storage.v1.DeleteRequest\x1a\x1a.storage.v1.DeleteResponse\x12I\n" +
	"\vDeleteByURL\x12\x1e.storage.v1.DeleteByURLRequest\x1a\x1a.storage.v1.DeleteResponse\x12T\n" +
	"\rUploadArchive\x12 .storage.v1.UploadArchiveRequest\x1a!.storage.v1.UploadArchiveResponse\x12Z\n" +
	"\x0fDownloadArchive\x12\".storage.v1.DownloadArchiveRequest\x1a#.storage.v1.DownloadArchiveResponse\x12Z\n" +
	"\x0fGetPresignedURL\x12\".storage.v1.GetPresignedURLRequest\x1a#.storage.v1.GetPresignedURLResponse\x12l\n" +
	"\x15GetPresignedUploadURL\x12(.storage.v1.GetPresignedUploadURLRequest\x1a).storage.v1.GetPresignedUploadURLResponseBNZLgithub.com/MuhibNayem/connectify-v2/shared-entity/proto/storage/v1;storagev1b\x06proto3"

var (
	file_shared_entity_proto_storage_v1_storage_proto_rawDescOnce sync.Once
	file_shared_entity_proto_storage_v1_storage_proto_rawDescData []byte
)

func file_shared_entity_proto_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_shared_entity_proto_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_shared_entity_proto_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_entity_proto_storage_v1_storage_proto_rawDesc), len(file_shared_entity_proto_storage_v1_storage_proto_rawDesc)))
	})
	return file_shared_entity_proto_storage_v1_storage_proto_rawDescData
}

var file_shared_entity_proto_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_shared_entity_proto_storage_v1_storage_proto_goTypes = []any{
	(*UploadRequest)(nil),                 // 0: storage.v1.UploadRequest
	(*UploadResponse)(nil),                // 1: storage.v1.UploadResponse
	(*UploadMultipleRequest)(nil),         // 2: storage.v1.UploadMultipleRequest
	(*FileUpload)(nil),                    // 3: storage.v1.FileUpload
	(*UploadMultipleResponse)(nil),        // 4: storage.v1.UploadMultipleResponse
	(*DeleteRequest)(nil),                 // 5: storage.v1.DeleteRequest
	(*DeleteByURLRequest)(nil),            // 6: storage.v1.DeleteByURLRequest
	(*DeleteResponse)(nil),                // 7: storage.v1.DeleteResponse
	(*UploadArchiveRequest)(nil),          // 8: storage.v1.UploadArchiveRequest
	(*UploadArchiveResponse)(nil),         // 9: storage.v1.UploadArchiveResponse
	(*DownloadArchiveRequest)(nil),        // 10: storage.v1.DownloadArchiveRequest
	(*DownloadArchiveResponse)(nil),       // 11: storage.v1.DownloadArchiveResponse
	(*GetPresignedURLRequest)(nil),        // 12: storage.v1.GetPresignedURLRequest
	(*GetPresignedURLResponse)(nil),       // 13: storage.v1.GetPresignedURLResponse
	(*GetPresignedUploadURLRequest)(nil),  // 14: storage.v1.GetPresignedUploadURLRequest
	(*GetPresignedUploadURLResponse)(nil), // 15: storage.v1.GetPresignedUploadURLResponse
}
var file_shared_entity_proto_storage_v1_storage_proto_depIdxs = []int32{
	3,  // 0: storage.v1.UploadMultipleRequest.files:type_name -> storage.v1.FileUpload
	1,  // 1: storage.v1.UploadMultipleResponse.results:type_name -> storage.v1.UploadResponse
	0,  // 2: storage.v1.StorageService.Upload:input_type -> storage.v1.UploadRequest
	2,  // 3: storage.v1.StorageService.UploadMultiple:input_type -> storage.v1.UploadMultipleRequest
	5,  // 4: storage.v1.StorageService.Delete:input_type -> storage.v1.DeleteRequest
	6,  // 5: storage.v1.StorageService.DeleteByURL:input_type -> storage.v1.DeleteByURLRequest
	8,  // 6: storage.v1.StorageService.UploadArchive:input_type -> storage.v1.UploadArchiveRequest
	10, // 7: storage.v1.StorageService.DownloadArchive:input_type -> storage.v1.DownloadArchiveRequest
	12, // 8: storage.v1.StorageService.GetPresignedURL:input_type -> storage.v1.GetPresignedURLRequest
	14, // 9: storage.v1.StorageService.GetPresignedUploadURL:input_type -> storage.v1.GetPresignedUploadURLRequest
	1,  // 10: storage.v1.StorageService.Upload:output_type -> storage.v1.UploadResponse
	4,  // 11: storage.v1.StorageService.UploadMultiple:output_type -> storage.v1.UploadMultipleResponse
	7,  // 12: storage.v1.StorageService.Delete:output_type -> storage.v1.DeleteResponse
	7,  // 13: storage.v1.StorageService.DeleteByURL:output_type -> storage.v1.DeleteResponse
	9,  // 14: storage.v1.StorageService.UploadArchive:output_type -> storage.v1.UploadArchiveResponse
	11, // 15: storage.v1.StorageService.DownloadArchive:output_type -> storage.v1.DownloadArchiveResponse
	13, // 16: storage.v1.StorageService.GetPresignedURL:output_type -> storage.v1.GetPresignedURLResponse
	15, // 17: storage.v1.StorageService.GetPresignedUploadURL:output_type -> storage.v1.GetPresignedUploadURLResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_shared_entity_proto_storage_v1_storage_proto_init() }
func file_shared_entity_proto_storage_v1_storage_proto_init() {
	if File_shared_entity_proto_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_entity_proto_storage_v1_storage_proto_rawDesc), len(file_shared_entity_proto_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_entity_proto_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_shared_entity_proto_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_shared_entity_proto_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_shared_entity_proto_storage_v1_storage_proto = out.File
	file_shared_entity_proto_storage_v1_storage_proto_goTypes = nil
	file_shared_entity_proto_storage_v1_storage_proto_depIdxs = nil
}
