// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: community/v1/community.proto

package communitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Community struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Slug                string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Category            string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Avatar              string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CoverImage          string                 `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Privacy             string                 `protobuf:"bytes,8,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Visibility          string                 `protobuf:"bytes,9,opt,name=visibility,proto3" json:"visibility,omitempty"`
	CreatorId           string                 `protobuf:"bytes,10,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Members             []string               `protobuf:"bytes,11,rep,name=members,proto3" json:"members,omitempty"`
	Admins              []string               `protobuf:"bytes,12,rep,name=admins,proto3" json:"admins,omitempty"`
	PendingMembers      []string               `protobuf:"bytes,13,rep,name=pending_members,json=pendingMembers,proto3" json:"pending_members,omitempty"`
	BannedUsers         []string               `protobuf:"bytes,14,rep,name=banned_users,json=bannedUsers,proto3" json:"banned_users,omitempty"`
	Settings            *CommunitySettings     `protobuf:"bytes,15,opt,name=settings,proto3" json:"settings,omitempty"`
	Rules               []*CommunityRule       `protobuf:"bytes,16,rep,name=rules,proto3" json:"rules,omitempty"`
	MembershipQuestions []string               `protobuf:"bytes,17,rep,name=membership_questions,json=membershipQuestions,proto3" json:"membership_questions,omitempty"`
	Stats               *CommunityStats        `protobuf:"bytes,18,opt,name=stats,proto3" json:"stats,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Computed fields (often returned in responses)
	IsMember      bool `protobuf:"varint,21,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	IsAdmin       bool `protobuf:"varint,22,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsPending     bool `protobuf:"varint,23,opt,name=is_pending,json=isPending,proto3" json:"is_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Community) Reset() {
	*x = Community{}
	mi := &file_community_v1_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Community) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Community) ProtoMessage() {}

func (x *Community) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Community.ProtoReflect.Descriptor instead.
func (*Community) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{0}
}

func (x *Community) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Community) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Community) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Community) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Community) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Community) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Community) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Community) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *Community) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Community) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Community) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Community) GetAdmins() []string {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *Community) GetPendingMembers() []string {
	if x != nil {
		return x.PendingMembers
	}
	return nil
}

func (x *Community) GetBannedUsers() []string {
	if x != nil {
		return x.BannedUsers
	}
	return nil
}

func (x *Community) GetSettings() *CommunitySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Community) GetRules() []*CommunityRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Community) GetMembershipQuestions() []string {
	if x != nil {
		return x.MembershipQuestions
	}
	return nil
}

func (x *Community) GetStats() *CommunityStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Community) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Community) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Community) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *Community) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *Community) GetIsPending() bool {
	if x != nil {
		return x.IsPending
	}
	return false
}

type CommunitySettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequirePostApproval  bool                   `protobuf:"varint,1,opt,name=require_post_approval,json=requirePostApproval,proto3" json:"require_post_approval,omitempty"`
	RequireJoinApproval  bool                   `protobuf:"varint,2,opt,name=require_join_approval,json=requireJoinApproval,proto3" json:"require_join_approval,omitempty"`
	AllowMemberPosts     bool                   `protobuf:"varint,3,opt,name=allow_member_posts,json=allowMemberPosts,proto3" json:"allow_member_posts,omitempty"`
	ShowGroupAffiliation bool                   `protobuf:"varint,4,opt,name=show_group_affiliation,json=showGroupAffiliation,proto3" json:"show_group_affiliation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CommunitySettings) Reset() {
	*x = CommunitySettings{}
	mi := &file_community_v1_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunitySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunitySettings) ProtoMessage() {}

func (x *CommunitySettings) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunitySettings.ProtoReflect.Descriptor instead.
func (*CommunitySettings) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{1}
}

func (x *CommunitySettings) GetRequirePostApproval() bool {
	if x != nil {
		return x.RequirePostApproval
	}
	return false
}

func (x *CommunitySettings) GetRequireJoinApproval() bool {
	if x != nil {
		return x.RequireJoinApproval
	}
	return false
}

func (x *CommunitySettings) GetAllowMemberPosts() bool {
	if x != nil {
		return x.AllowMemberPosts
	}
	return false
}

func (x *CommunitySettings) GetShowGroupAffiliation() bool {
	if x != nil {
		return x.ShowGroupAffiliation
	}
	return false
}

type CommunityRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityRule) Reset() {
	*x = CommunityRule{}
	mi := &file_community_v1_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityRule) ProtoMessage() {}

func (x *CommunityRule) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityRule.ProtoReflect.Descriptor instead.
func (*CommunityRule) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{2}
}

func (x *CommunityRule) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommunityRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CommunityStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberCount   int64                  `protobuf:"varint,1,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	PostCount     int64                  `protobuf:"varint,2,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityStats) Reset() {
	*x = CommunityStats{}
	mi := &file_community_v1_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityStats) ProtoMessage() {}

func (x *CommunityStats) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityStats.ProtoReflect.Descriptor instead.
func (*CommunityStats) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{3}
}

func (x *CommunityStats) GetMemberCount() int64 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *CommunityStats) GetPostCount() int64 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

type CreateCommunityRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CreatorId           string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category            string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Avatar              string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CoverImage          string                 `protobuf:"bytes,6,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Privacy             string                 `protobuf:"bytes,7,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Visibility          string                 `protobuf:"bytes,8,opt,name=visibility,proto3" json:"visibility,omitempty"`
	RequirePostApproval bool                   `protobuf:"varint,9,opt,name=require_post_approval,json=requirePostApproval,proto3" json:"require_post_approval,omitempty"`
	RequireJoinApproval bool                   `protobuf:"varint,10,opt,name=require_join_approval,json=requireJoinApproval,proto3" json:"require_join_approval,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateCommunityRequest) Reset() {
	*x = CreateCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommunityRequest) ProtoMessage() {}

func (x *CreateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommunityRequest.ProtoReflect.Descriptor instead.
func (*CreateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCommunityRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateCommunityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCommunityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCommunityRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateCommunityRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateCommunityRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *CreateCommunityRequest) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *CreateCommunityRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreateCommunityRequest) GetRequirePostApproval() bool {
	if x != nil {
		return x.RequirePostApproval
	}
	return false
}

func (x *CreateCommunityRequest) GetRequireJoinApproval() bool {
	if x != nil {
		return x.RequireJoinApproval
	}
	return false
}

type CreateCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommunityResponse) Reset() {
	*x = CreateCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommunityResponse) ProtoMessage() {}

func (x *CreateCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommunityResponse.ProtoReflect.Descriptor instead.
func (*CreateCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type GetCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ViewerId      string                 `protobuf:"bytes,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // Optional, to calculate is_member/is_admin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityRequest) Reset() {
	*x = GetCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityRequest) ProtoMessage() {}

func (x *GetCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *GetCommunityRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

type GetCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityResponse) Reset() {
	*x = GetCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityResponse) ProtoMessage() {}

func (x *GetCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityResponse.ProtoReflect.Descriptor instead.
func (*GetCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type UpdateCommunityRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CommunityId          string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Actor (must be admin)
	Name                 *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description          *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category             *string                `protobuf:"bytes,5,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Avatar               *string                `protobuf:"bytes,6,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	CoverImage           *string                `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3,oneof" json:"cover_image,omitempty"`
	Privacy              *string                `protobuf:"bytes,8,opt,name=privacy,proto3,oneof" json:"privacy,omitempty"`
	Visibility           *string                `protobuf:"bytes,9,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`
	RequirePostApproval  *bool                  `protobuf:"varint,10,opt,name=require_post_approval,json=requirePostApproval,proto3,oneof" json:"require_post_approval,omitempty"`
	RequireJoinApproval  *bool                  `protobuf:"varint,11,opt,name=require_join_approval,json=requireJoinApproval,proto3,oneof" json:"require_join_approval,omitempty"`
	AllowMemberPosts     *bool                  `protobuf:"varint,12,opt,name=allow_member_posts,json=allowMemberPosts,proto3,oneof" json:"allow_member_posts,omitempty"`
	ShowGroupAffiliation *bool                  `protobuf:"varint,13,opt,name=show_group_affiliation,json=showGroupAffiliation,proto3,oneof" json:"show_group_affiliation,omitempty"`
	Rules                []*CommunityRule       `protobuf:"bytes,14,rep,name=rules,proto3" json:"rules,omitempty"`
	MembershipQuestions  []string               `protobuf:"bytes,15,rep,name=membership_questions,json=membershipQuestions,proto3" json:"membership_questions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateCommunityRequest) Reset() {
	*x = UpdateCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityRequest) ProtoMessage() {}

func (x *UpdateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *UpdateCommunityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCommunityRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCommunityRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCommunityRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateCommunityRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UpdateCommunityRequest) GetCoverImage() string {
	if x != nil && x.CoverImage != nil {
		return *x.CoverImage
	}
	return ""
}

func (x *UpdateCommunityRequest) GetPrivacy() string {
	if x != nil && x.Privacy != nil {
		return *x.Privacy
	}
	return ""
}

func (x *UpdateCommunityRequest) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *UpdateCommunityRequest) GetRequirePostApproval() bool {
	if x != nil && x.RequirePostApproval != nil {
		return *x.RequirePostApproval
	}
	return false
}

func (x *UpdateCommunityRequest) GetRequireJoinApproval() bool {
	if x != nil && x.RequireJoinApproval != nil {
		return *x.RequireJoinApproval
	}
	return false
}

func (x *UpdateCommunityRequest) GetAllowMemberPosts() bool {
	if x != nil && x.AllowMemberPosts != nil {
		return *x.AllowMemberPosts
	}
	return false
}

func (x *UpdateCommunityRequest) GetShowGroupAffiliation() bool {
	if x != nil && x.ShowGroupAffiliation != nil {
		return *x.ShowGroupAffiliation
	}
	return false
}

func (x *UpdateCommunityRequest) GetRules() []*CommunityRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *UpdateCommunityRequest) GetMembershipQuestions() []string {
	if x != nil {
		return x.MembershipQuestions
	}
	return nil
}

type UpdateCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityResponse) Reset() {
	*x = UpdateCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityResponse) ProtoMessage() {}

func (x *UpdateCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type ListCommunitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	ViewerId      string                 `protobuf:"bytes,4,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // To filter hidden
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesRequest) Reset() {
	*x = ListCommunitiesRequest{}
	mi := &file_community_v1_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesRequest) ProtoMessage() {}

func (x *ListCommunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCommunitiesRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{10}
}

func (x *ListCommunitiesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListCommunitiesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommunitiesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommunitiesRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

type ListCommunitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []*Community           `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesResponse) Reset() {
	*x = ListCommunitiesResponse{}
	mi := &file_community_v1_community_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesResponse) ProtoMessage() {}

func (x *ListCommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{11}
}

func (x *ListCommunitiesResponse) GetCommunities() []*Community {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *ListCommunitiesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUserCommunitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCommunitiesRequest) Reset() {
	*x = GetUserCommunitiesRequest{}
	mi := &file_community_v1_community_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCommunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCommunitiesRequest) ProtoMessage() {}

func (x *GetUserCommunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCommunitiesRequest.ProtoReflect.Descriptor instead.
func (*GetUserCommunitiesRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserCommunitiesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserCommunitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []*Community           `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCommunitiesResponse) Reset() {
	*x = GetUserCommunitiesResponse{}
	mi := &file_community_v1_community_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCommunitiesResponse) ProtoMessage() {}

func (x *GetUserCommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCommunitiesResponse.ProtoReflect.Descriptor instead.
func (*GetUserCommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserCommunitiesResponse) GetCommunities() []*Community {
	if x != nil {
		return x.Communities
	}
	return nil
}

type JoinCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCommunityRequest) Reset() {
	*x = JoinCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCommunityRequest) ProtoMessage() {}

func (x *JoinCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCommunityRequest.ProtoReflect.Descriptor instead.
func (*JoinCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{14}
}

func (x *JoinCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *JoinCommunityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCommunityResponse) Reset() {
	*x = JoinCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCommunityResponse) ProtoMessage() {}

func (x *JoinCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCommunityResponse.ProtoReflect.Descriptor instead.
func (*JoinCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{15}
}

func (x *JoinCommunityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinCommunityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LeaveCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User leaving
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCommunityRequest) Reset() {
	*x = LeaveCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommunityRequest) ProtoMessage() {}

func (x *LeaveCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommunityRequest.ProtoReflect.Descriptor instead.
func (*LeaveCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{16}
}

func (x *LeaveCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *LeaveCommunityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCommunityResponse) Reset() {
	*x = LeaveCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommunityResponse) ProtoMessage() {}

func (x *LeaveCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommunityResponse.ProtoReflect.Descriptor instead.
func (*LeaveCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{17}
}

func (x *LeaveCommunityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ApproveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`    // Admin
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // User to approve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveMemberRequest) Reset() {
	*x = ApproveMemberRequest{}
	mi := &file_community_v1_community_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveMemberRequest) ProtoMessage() {}

func (x *ApproveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveMemberRequest.ProtoReflect.Descriptor instead.
func (*ApproveMemberRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{18}
}

func (x *ApproveMemberRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *ApproveMemberRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ApproveMemberRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type ApproveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveMemberResponse) Reset() {
	*x = ApproveMemberResponse{}
	mi := &file_community_v1_community_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveMemberResponse) ProtoMessage() {}

func (x *ApproveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveMemberResponse.ProtoReflect.Descriptor instead.
func (*ApproveMemberResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{19}
}

func (x *ApproveMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RejectMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectMemberRequest) Reset() {
	*x = RejectMemberRequest{}
	mi := &file_community_v1_community_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectMemberRequest) ProtoMessage() {}

func (x *RejectMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectMemberRequest.ProtoReflect.Descriptor instead.
func (*RejectMemberRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{20}
}

func (x *RejectMemberRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *RejectMemberRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RejectMemberRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type RejectMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectMemberResponse) Reset() {
	*x = RejectMemberResponse{}
	mi := &file_community_v1_community_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectMemberResponse) ProtoMessage() {}

func (x *RejectMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectMemberResponse.ProtoReflect.Descriptor instead.
func (*RejectMemberResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{21}
}

func (x *RejectMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ViewerId      string                 `protobuf:"bytes,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_community_v1_community_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{22}
}

func (x *GetMembersRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *GetMembersRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *GetMembersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMembersRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type UserShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserShort) Reset() {
	*x = UserShort{}
	mi := &file_community_v1_community_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserShort) ProtoMessage() {}

func (x *UserShort) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserShort.ProtoReflect.Descriptor instead.
func (*UserShort) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{23}
}

func (x *UserShort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserShort) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserShort) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserShort) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetMembersResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Members []*UserShort           `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"` // Service needs to return UserShorts? Or just IDs?
	// Ideally CommunityService shouldn't handle User details, but to keep existing contract fast, maybe it does?
	// Actually MessagingApp controller gets IDs and populates Users usually?
	// In `CommunityService.go`, GetMembers calls Repo.GetMembers which returns `[]models.User`.
	// Wait, CommunityRepo joins with Users table?
	// If we split services, CommunityService CANNOT join Users table. It can only return IDs.
	// Refactoring: CommunityService returns IDs, MessagingApp (Gateway) fetches User details from UserService.
	// BUT the user asked to "extract community service".
	// If I return IDs, I change the internal logic significantly.
	// Let's check `community_repository.go` to see if it does a lookup.
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	mi := &file_community_v1_community_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{24}
}

func (x *GetMembersResponse) GetMembers() []*UserShort {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetMembersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAdminsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminsRequest) Reset() {
	*x = GetAdminsRequest{}
	mi := &file_community_v1_community_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminsRequest) ProtoMessage() {}

func (x *GetAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminsRequest.ProtoReflect.Descriptor instead.
func (*GetAdminsRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{25}
}

func (x *GetAdminsRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type GetAdminsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*UserShort           `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminsResponse) Reset() {
	*x = GetAdminsResponse{}
	mi := &file_community_v1_community_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminsResponse) ProtoMessage() {}

func (x *GetAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminsResponse.ProtoReflect.Descriptor instead.
func (*GetAdminsResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{26}
}

func (x *GetAdminsResponse) GetAdmins() []*UserShort {
	if x != nil {
		return x.Admins
	}
	return nil
}

type GetPendingMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingMembersRequest) Reset() {
	*x = GetPendingMembersRequest{}
	mi := &file_community_v1_community_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingMembersRequest) ProtoMessage() {}

func (x *GetPendingMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingMembersRequest.ProtoReflect.Descriptor instead.
func (*GetPendingMembersRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{27}
}

func (x *GetPendingMembersRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *GetPendingMembersRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *GetPendingMembersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPendingMembersRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetPendingMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*UserShort           `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingMembersResponse) Reset() {
	*x = GetPendingMembersResponse{}
	mi := &file_community_v1_community_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingMembersResponse) ProtoMessage() {}

func (x *GetPendingMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingMembersResponse.ProtoReflect.Descriptor instead.
func (*GetPendingMembersResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{28}
}

func (x *GetPendingMembersResponse) GetMembers() []*UserShort {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetPendingMembersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_community_v1_community_proto protoreflect.FileDescriptor

const file_community_v1_community_proto_rawDesc = "" +
	"\n" +
	"\x1ccommunity/v1/community.proto\x12\fcommunity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x06\n" +
	"\tCommunity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vcover_image\x18\a \x01(\tR\n" +
	"coverImage\x12\x18\n" +
	"\aprivacy\x18\b \x01(\tR\aprivacy\x12\x1e\n" +
	"\n" +
	"visibility\x18\t \x01(\tR\n" +
	"visibility\x12\x1d\n" +
	"\n" +
	"creator_id\x18\n" +
	" \x01(\tR\tcreatorId\x12\x18\n" +
	"\amembers\x18\v \x03(\tR\amembers\x12\x16\n" +
	"\x06admins\x18\f \x03(\tR\x06admins\x12'\n" +
	"\x0fpending_members\x18\r \x03(\tR\x0ependingMembers\x12!\n" +
	"\fbanned_users\x18\x0e \x03(\tR\vbannedUsers\x12;\n" +
	"\bsettings\x18\x0f \x01(\v2\x1f.community.v1.CommunitySettingsR\bsettings\x121\n" +
	"\x05rules\x18\x10 \x03(\v2\x1b.community.v1.CommunityRuleR\x05rules\x121\n" +
	"\x14membership_questions\x18\x11 \x03(\tR\x13membershipQuestions\x122\n" +
	"\x05stats\x18\x12 \x01(\v2\x1c.community.v1.CommunityStatsR\x05stats\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tis_member\x18\x15 \x01(\bR\bisMember\x12\x19\n" +
	"\bis_admin\x18\x16 \x01(\bR\aisAdmin\x12\x1d\n" +
	"\n" +
	"is_pending\x18\x17 \x01(\bR\tisPending\"\xdf\x01\n" +
	"\x11CommunitySettings\x122\n" +
	"\x15require_post_approval\x18\x01 \x01(\bR\x13requirePostApproval\x122\n" +
	"\x15require_join_approval\x18\x02 \x01(\bR\x13requireJoinApproval\x12,\n" +
	"\x12allow_member_posts\x18\x03 \x01(\bR\x10allowMemberPosts\x124\n" +
	"\x16show_group_affiliation\x18\x04 \x01(\bR\x14showGroupAffiliation\"G\n" +
	"\rCommunityRule\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"R\n" +
	"\x0eCommunityStats\x12!\n" +
	"\fmember_count\x18\x01 \x01(\x03R\vmemberCount\x12\x1d\n" +
	"\n" +
	"post_count\x18\x02 \x01(\x03R\tpostCount\"\xe4\x02\n" +
	"\x16CreateCommunityRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vcover_image\x18\x06 \x01(\tR\n" +
	"coverImage\x12\x18\n" +
	"\aprivacy\x18\a \x01(\tR\aprivacy\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\tR\n" +
	"visibility\x122\n" +
	"\x15require_post_approval\x18\t \x01(\bR\x13requirePostApproval\x122\n" +
	"\x15require_join_approval\x18\n" +
	" \x01(\bR\x13requireJoinApproval\"P\n" +
	"\x17CreateCommunityResponse\x125\n" +
	"\tcommunity\x18\x01 \x01(\v2\x17.community.v1.CommunityR\tcommunity\"U\n" +
	"\x13GetCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\tR\bviewerId\"M\n" +
	"\x14GetCommunityResponse\x125\n" +
	"\tcommunity\x18\x01 \x01(\v2\x17.community.v1.CommunityR\tcommunity\"\xc4\x06\n" +
	"\x16UpdateCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x05 \x01(\tH\x02R\bcategory\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x06 \x01(\tH\x03R\x06avatar\x88\x01\x01\x12$\n" +
	"\vcover_image\x18\a \x01(\tH\x04R\n" +
	"coverImage\x88\x01\x01\x12\x1d\n" +
	"\aprivacy\x18\b \x01(\tH\x05R\aprivacy\x88\x01\x01\x12#\n" +
	"\n" +
	"visibility\x18\t \x01(\tH\x06R\n" +
	"visibility\x88\x01\x01\x127\n" +
	"\x15require_post_approval\x18\n" +
	" \x01(\bH\aR\x13requirePostApproval\x88\x01\x01\x127\n" +
	"\x15require_join_approval\x18\v \x01(\bH\bR\x13requireJoinApproval\x88\x01\x01\x121\n" +
	"\x12allow_member_posts\x18\f \x01(\bH\tR\x10allowMemberPosts\x88\x01\x01\x129\n" +
	"\x16show_group_affiliation\x18\r \x01(\bH\n" +
	"R\x14showGroupAffiliation\x88\x01\x01\x121\n" +
	"\x05rules\x18\x0e \x03(\v2\x1b.community.v1.CommunityRuleR\x05rules\x121\n" +
	"\x14membership_questions\x18\x0f \x03(\tR\x13membershipQuestionsB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_categoryB\t\n" +
	"\a_avatarB\x0e\n" +
	"\f_cover_imageB\n" +
	"\n" +
	"\b_privacyB\r\n" +
	"\v_visibilityB\x18\n" +
	"\x16_require_post_approvalB\x18\n" +
	"\x16_require_join_approvalB\x15\n" +
	"\x13_allow_member_postsB\x19\n" +
	"\x17_show_group_affiliation\"P\n" +
	"\x17UpdateCommunityResponse\x125\n" +
	"\tcommunity\x18\x01 \x01(\v2\x17.community.v1.CommunityR\tcommunity\"u\n" +
	"\x16ListCommunitiesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tviewer_id\x18\x04 \x01(\tR\bviewerId\"j\n" +
	"\x17ListCommunitiesResponse\x129\n" +
	"\vcommunities\x18\x01 \x03(\v2\x17.community.v1.CommunityR\vcommunities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"4\n" +
	"\x19GetUserCommunitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"W\n" +
	"\x1aGetUserCommunitiesResponse\x129\n" +
	"\vcommunities\x18\x01 \x03(\v2\x17.community.v1.CommunityR\vcommunities\"R\n" +
	"\x14JoinCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x15JoinCommunityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x15LeaveCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"2\n" +
	"\x16LeaveCommunityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"q\n" +
	"\x14ApproveMemberRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"1\n" +
	"\x15ApproveMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"p\n" +
	"\x13RejectMemberRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"0\n" +
	"\x14RejectMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"}\n" +
	"\x11GetMembersRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\tR\bviewerId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\"l\n" +
	"\tUserShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"]\n" +
	"\x12GetMembersResponse\x121\n" +
	"\amembers\x18\x01 \x03(\v2\x17.community.v1.UserShortR\amembers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"5\n" +
	"\x10GetAdminsRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"D\n" +
	"\x11GetAdminsResponse\x12/\n" +
	"\x06admins\x18\x01 \x03(\v2\x17.community.v1.UserShortR\x06admins\"\x82\x01\n" +
	"\x18GetPendingMembersRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\"d\n" +
	"\x19GetPendingMembersResponse\x121\n" +
	"\amembers\x18\x01 \x03(\v2\x17.community.v1.UserShortR\amembers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xdf\b\n" +
	"\x10CommunityService\x12^\n" +
	"\x0fCreateCommunity\x12$.community.v1.CreateCommunityRequest\x1a%.community.v1.CreateCommunityResponse\x12U\n" +
	"\fGetCommunity\x12!.community.v1.GetCommunityRequest\x1a\".community.v1.GetCommunityResponse\x12^\n" +
	"\x0fUpdateCommunity\x12$.community.v1.UpdateCommunityRequest\x1a%.community.v1.UpdateCommunityResponse\x12^\n" +
	"\x0fListCommunities\x12$.community.v1.ListCommunitiesRequest\x1a%.community.v1.ListCommunitiesResponse\x12g\n" +
	"\x12GetUserCommunities\x12'.community.v1.GetUserCommunitiesRequest\x1a(.community.v1.GetUserCommunitiesResponse\x12X\n" +
	"\rJoinCommunity\x12\".community.v1.JoinCommunityRequest\x1a#.community.v1.JoinCommunityResponse\x12[\n" +
	"\x0eLeaveCommunity\x12#.community.v1.LeaveCommunityRequest\x1a$.community.v1.LeaveCommunityResponse\x12X\n" +
	"\rApproveMember\x12\".community.v1.ApproveMemberRequest\x1a#.community.v1.ApproveMemberResponse\x12U\n" +
	"\fRejectMember\x12!.community.v1.RejectMemberRequest\x1a\".community.v1.RejectMemberResponse\x12O\n" +
	"\n" +
	"GetMembers\x12\x1f.community.v1.GetMembersRequest\x1a .community.v1.GetMembersResponse\x12L\n" +
	"\tGetAdmins\x12\x1e.community.v1.GetAdminsRequest\x1a\x1f.community.v1.GetAdminsResponse\x12d\n" +
	"\x11GetPendingMembers\x12&.community.v1.GetPendingMembersRequest\x1a'.community.v1.GetPendingMembersResponseBRZPgithub.com/MuhibNayem/connectify-v2/shared-entity/proto/community/v1;communitypbb\x06proto3"

var (
	file_community_v1_community_proto_rawDescOnce sync.Once
	file_community_v1_community_proto_rawDescData []byte
)

func file_community_v1_community_proto_rawDescGZIP() []byte {
	file_community_v1_community_proto_rawDescOnce.Do(func() {
		file_community_v1_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_v1_community_proto_rawDesc), len(file_community_v1_community_proto_rawDesc)))
	})
	return file_community_v1_community_proto_rawDescData
}

var file_community_v1_community_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_community_v1_community_proto_goTypes = []any{
	(*Community)(nil),                  // 0: community.v1.Community
	(*CommunitySettings)(nil),          // 1: community.v1.CommunitySettings
	(*CommunityRule)(nil),              // 2: community.v1.CommunityRule
	(*CommunityStats)(nil),             // 3: community.v1.CommunityStats
	(*CreateCommunityRequest)(nil),     // 4: community.v1.CreateCommunityRequest
	(*CreateCommunityResponse)(nil),    // 5: community.v1.CreateCommunityResponse
	(*GetCommunityRequest)(nil),        // 6: community.v1.GetCommunityRequest
	(*GetCommunityResponse)(nil),       // 7: community.v1.GetCommunityResponse
	(*UpdateCommunityRequest)(nil),     // 8: community.v1.UpdateCommunityRequest
	(*UpdateCommunityResponse)(nil),    // 9: community.v1.UpdateCommunityResponse
	(*ListCommunitiesRequest)(nil),     // 10: community.v1.ListCommunitiesRequest
	(*ListCommunitiesResponse)(nil),    // 11: community.v1.ListCommunitiesResponse
	(*GetUserCommunitiesRequest)(nil),  // 12: community.v1.GetUserCommunitiesRequest
	(*GetUserCommunitiesResponse)(nil), // 13: community.v1.GetUserCommunitiesResponse
	(*JoinCommunityRequest)(nil),       // 14: community.v1.JoinCommunityRequest
	(*JoinCommunityResponse)(nil),      // 15: community.v1.JoinCommunityResponse
	(*LeaveCommunityRequest)(nil),      // 16: community.v1.LeaveCommunityRequest
	(*LeaveCommunityResponse)(nil),     // 17: community.v1.LeaveCommunityResponse
	(*ApproveMemberRequest)(nil),       // 18: community.v1.ApproveMemberRequest
	(*ApproveMemberResponse)(nil),      // 19: community.v1.ApproveMemberResponse
	(*RejectMemberRequest)(nil),        // 20: community.v1.RejectMemberRequest
	(*RejectMemberResponse)(nil),       // 21: community.v1.RejectMemberResponse
	(*GetMembersRequest)(nil),          // 22: community.v1.GetMembersRequest
	(*UserShort)(nil),                  // 23: community.v1.UserShort
	(*GetMembersResponse)(nil),         // 24: community.v1.GetMembersResponse
	(*GetAdminsRequest)(nil),           // 25: community.v1.GetAdminsRequest
	(*GetAdminsResponse)(nil),          // 26: community.v1.GetAdminsResponse
	(*GetPendingMembersRequest)(nil),   // 27: community.v1.GetPendingMembersRequest
	(*GetPendingMembersResponse)(nil),  // 28: community.v1.GetPendingMembersResponse
	(*timestamppb.Timestamp)(nil),      // 29: google.protobuf.Timestamp
}
var file_community_v1_community_proto_depIdxs = []int32{
	1,  // 0: community.v1.Community.settings:type_name -> community.v1.CommunitySettings
	2,  // 1: community.v1.Community.rules:type_name -> community.v1.CommunityRule
	3,  // 2: community.v1.Community.stats:type_name -> community.v1.CommunityStats
	29, // 3: community.v1.Community.created_at:type_name -> google.protobuf.Timestamp
	29, // 4: community.v1.Community.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: community.v1.CreateCommunityResponse.community:type_name -> community.v1.Community
	0,  // 6: community.v1.GetCommunityResponse.community:type_name -> community.v1.Community
	2,  // 7: community.v1.UpdateCommunityRequest.rules:type_name -> community.v1.CommunityRule
	0,  // 8: community.v1.UpdateCommunityResponse.community:type_name -> community.v1.Community
	0,  // 9: community.v1.ListCommunitiesResponse.communities:type_name -> community.v1.Community
	0,  // 10: community.v1.GetUserCommunitiesResponse.communities:type_name -> community.v1.Community
	23, // 11: community.v1.GetMembersResponse.members:type_name -> community.v1.UserShort
	23, // 12: community.v1.GetAdminsResponse.admins:type_name -> community.v1.UserShort
	23, // 13: community.v1.GetPendingMembersResponse.members:type_name -> community.v1.UserShort
	4,  // 14: community.v1.CommunityService.CreateCommunity:input_type -> community.v1.CreateCommunityRequest
	6,  // 15: community.v1.CommunityService.GetCommunity:input_type -> community.v1.GetCommunityRequest
	8,  // 16: community.v1.CommunityService.UpdateCommunity:input_type -> community.v1.UpdateCommunityRequest
	10, // 17: community.v1.CommunityService.ListCommunities:input_type -> community.v1.ListCommunitiesRequest
	12, // 18: community.v1.CommunityService.GetUserCommunities:input_type -> community.v1.GetUserCommunitiesRequest
	14, // 19: community.v1.CommunityService.JoinCommunity:input_type -> community.v1.JoinCommunityRequest
	16, // 20: community.v1.CommunityService.LeaveCommunity:input_type -> community.v1.LeaveCommunityRequest
	18, // 21: community.v1.CommunityService.ApproveMember:input_type -> community.v1.ApproveMemberRequest
	20, // 22: community.v1.CommunityService.RejectMember:input_type -> community.v1.RejectMemberRequest
	22, // 23: community.v1.CommunityService.GetMembers:input_type -> community.v1.GetMembersRequest
	25, // 24: community.v1.CommunityService.GetAdmins:input_type -> community.v1.GetAdminsRequest
	27, // 25: community.v1.CommunityService.GetPendingMembers:input_type -> community.v1.GetPendingMembersRequest
	5,  // 26: community.v1.CommunityService.CreateCommunity:output_type -> community.v1.CreateCommunityResponse
	7,  // 27: community.v1.CommunityService.GetCommunity:output_type -> community.v1.GetCommunityResponse
	9,  // 28: community.v1.CommunityService.UpdateCommunity:output_type -> community.v1.UpdateCommunityResponse
	11, // 29: community.v1.CommunityService.ListCommunities:output_type -> community.v1.ListCommunitiesResponse
	13, // 30: community.v1.CommunityService.GetUserCommunities:output_type -> community.v1.GetUserCommunitiesResponse
	15, // 31: community.v1.CommunityService.JoinCommunity:output_type -> community.v1.JoinCommunityResponse
	17, // 32: community.v1.CommunityService.LeaveCommunity:output_type -> community.v1.LeaveCommunityResponse
	19, // 33: community.v1.CommunityService.ApproveMember:output_type -> community.v1.ApproveMemberResponse
	21, // 34: community.v1.CommunityService.RejectMember:output_type -> community.v1.RejectMemberResponse
	24, // 35: community.v1.CommunityService.GetMembers:output_type -> community.v1.GetMembersResponse
	26, // 36: community.v1.CommunityService.GetAdmins:output_type -> community.v1.GetAdminsResponse
	28, // 37: community.v1.CommunityService.GetPendingMembers:output_type -> community.v1.GetPendingMembersResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_community_v1_community_proto_init() }
func file_community_v1_community_proto_init() {
	if File_community_v1_community_proto != nil {
		return
	}
	file_community_v1_community_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_v1_community_proto_rawDesc), len(file_community_v1_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_v1_community_proto_goTypes,
		DependencyIndexes: file_community_v1_community_proto_depIdxs,
		MessageInfos:      file_community_v1_community_proto_msgTypes,
	}.Build()
	File_community_v1_community_proto = out.File
	file_community_v1_community_proto_goTypes = nil
	file_community_v1_community_proto_depIdxs = nil
}
