// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/story/v1/story.proto

package storypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoryService_CreateStory_FullMethodName     = "/story.v1.StoryService/CreateStory"
	StoryService_GetStory_FullMethodName        = "/story.v1.StoryService/GetStory"
	StoryService_DeleteStory_FullMethodName     = "/story.v1.StoryService/DeleteStory"
	StoryService_GetStoriesFeed_FullMethodName  = "/story.v1.StoryService/GetStoriesFeed"
	StoryService_GetUserStories_FullMethodName  = "/story.v1.StoryService/GetUserStories"
	StoryService_RecordView_FullMethodName      = "/story.v1.StoryService/RecordView"
	StoryService_ReactToStory_FullMethodName    = "/story.v1.StoryService/ReactToStory"
	StoryService_GetStoryViewers_FullMethodName = "/story.v1.StoryService/GetStoryViewers"
)

// StoryServiceClient is the client API for StoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StoryService provides story management APIs
type StoryServiceClient interface {
	// Create a new story
	CreateStory(ctx context.Context, in *CreateStoryRequest, opts ...grpc.CallOption) (*StoryResponse, error)
	// Get a single story by ID
	GetStory(ctx context.Context, in *GetStoryRequest, opts ...grpc.CallOption) (*StoryResponse, error)
	// Delete a story
	DeleteStory(ctx context.Context, in *DeleteStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get stories feed for a user (paginated, with privacy filtering)
	GetStoriesFeed(ctx context.Context, in *GetStoriesFeedRequest, opts ...grpc.CallOption) (*StoriesFeedResponse, error)
	// Get all stories for a specific user
	GetUserStories(ctx context.Context, in *GetUserStoriesRequest, opts ...grpc.CallOption) (*StoriesResponse, error)
	// Record a view on a story
	RecordView(ctx context.Context, in *RecordViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Add a reaction to a story
	ReactToStory(ctx context.Context, in *ReactToStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get story viewers with their reactions
	GetStoryViewers(ctx context.Context, in *GetStoryViewersRequest, opts ...grpc.CallOption) (*StoryViewersResponse, error)
}

type storyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoryServiceClient(cc grpc.ClientConnInterface) StoryServiceClient {
	return &storyServiceClient{cc}
}

func (c *storyServiceClient) CreateStory(ctx context.Context, in *CreateStoryRequest, opts ...grpc.CallOption) (*StoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoryResponse)
	err := c.cc.Invoke(ctx, StoryService_CreateStory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) GetStory(ctx context.Context, in *GetStoryRequest, opts ...grpc.CallOption) (*StoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoryResponse)
	err := c.cc.Invoke(ctx, StoryService_GetStory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) DeleteStory(ctx context.Context, in *DeleteStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StoryService_DeleteStory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) GetStoriesFeed(ctx context.Context, in *GetStoriesFeedRequest, opts ...grpc.CallOption) (*StoriesFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoriesFeedResponse)
	err := c.cc.Invoke(ctx, StoryService_GetStoriesFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) GetUserStories(ctx context.Context, in *GetUserStoriesRequest, opts ...grpc.CallOption) (*StoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoriesResponse)
	err := c.cc.Invoke(ctx, StoryService_GetUserStories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) RecordView(ctx context.Context, in *RecordViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StoryService_RecordView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) ReactToStory(ctx context.Context, in *ReactToStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StoryService_ReactToStory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) GetStoryViewers(ctx context.Context, in *GetStoryViewersRequest, opts ...grpc.CallOption) (*StoryViewersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoryViewersResponse)
	err := c.cc.Invoke(ctx, StoryService_GetStoryViewers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoryServiceServer is the server API for StoryService service.
// All implementations must embed UnimplementedStoryServiceServer
// for forward compatibility.
//
// StoryService provides story management APIs
type StoryServiceServer interface {
	// Create a new story
	CreateStory(context.Context, *CreateStoryRequest) (*StoryResponse, error)
	// Get a single story by ID
	GetStory(context.Context, *GetStoryRequest) (*StoryResponse, error)
	// Delete a story
	DeleteStory(context.Context, *DeleteStoryRequest) (*emptypb.Empty, error)
	// Get stories feed for a user (paginated, with privacy filtering)
	GetStoriesFeed(context.Context, *GetStoriesFeedRequest) (*StoriesFeedResponse, error)
	// Get all stories for a specific user
	GetUserStories(context.Context, *GetUserStoriesRequest) (*StoriesResponse, error)
	// Record a view on a story
	RecordView(context.Context, *RecordViewRequest) (*emptypb.Empty, error)
	// Add a reaction to a story
	ReactToStory(context.Context, *ReactToStoryRequest) (*emptypb.Empty, error)
	// Get story viewers with their reactions
	GetStoryViewers(context.Context, *GetStoryViewersRequest) (*StoryViewersResponse, error)
	mustEmbedUnimplementedStoryServiceServer()
}

// UnimplementedStoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoryServiceServer struct{}

func (UnimplementedStoryServiceServer) CreateStory(context.Context, *CreateStoryRequest) (*StoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStory not implemented")
}
func (UnimplementedStoryServiceServer) GetStory(context.Context, *GetStoryRequest) (*StoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStory not implemented")
}
func (UnimplementedStoryServiceServer) DeleteStory(context.Context, *DeleteStoryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStory not implemented")
}
func (UnimplementedStoryServiceServer) GetStoriesFeed(context.Context, *GetStoriesFeedRequest) (*StoriesFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoriesFeed not implemented")
}
func (UnimplementedStoryServiceServer) GetUserStories(context.Context, *GetUserStoriesRequest) (*StoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStories not implemented")
}
func (UnimplementedStoryServiceServer) RecordView(context.Context, *RecordViewRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordView not implemented")
}
func (UnimplementedStoryServiceServer) ReactToStory(context.Context, *ReactToStoryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReactToStory not implemented")
}
func (UnimplementedStoryServiceServer) GetStoryViewers(context.Context, *GetStoryViewersRequest) (*StoryViewersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoryViewers not implemented")
}
func (UnimplementedStoryServiceServer) mustEmbedUnimplementedStoryServiceServer() {}
func (UnimplementedStoryServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoryServiceServer will
// result in compilation errors.
type UnsafeStoryServiceServer interface {
	mustEmbedUnimplementedStoryServiceServer()
}

func RegisterStoryServiceServer(s grpc.ServiceRegistrar, srv StoryServiceServer) {
	// If the following call panics, it indicates UnimplementedStoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoryService_ServiceDesc, srv)
}

func _StoryService_CreateStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).CreateStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryService_CreateStory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).CreateStory(ctx, req.(*CreateStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_GetStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).GetStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryService_GetStory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).GetStory(ctx, req.(*GetStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_DeleteStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).DeleteStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryService_DeleteStory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).DeleteStory(ctx, req.(*DeleteStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_GetStoriesFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoriesFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).GetStoriesFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryService_GetStoriesFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).GetStoriesFeed(ctx, req.(*GetStoriesFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_GetUserStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).GetUserStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryService_GetUserStories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).GetUserStories(ctx, req.(*GetUserStoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_RecordView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).RecordView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryService_RecordView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).RecordView(ctx, req.(*RecordViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_ReactToStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactToStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).ReactToStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryService_ReactToStory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).ReactToStory(ctx, req.(*ReactToStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_GetStoryViewers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoryViewersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).GetStoryViewers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryService_GetStoryViewers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).GetStoryViewers(ctx, req.(*GetStoryViewersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoryService_ServiceDesc is the grpc.ServiceDesc for StoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "story.v1.StoryService",
	HandlerType: (*StoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStory",
			Handler:    _StoryService_CreateStory_Handler,
		},
		{
			MethodName: "GetStory",
			Handler:    _StoryService_GetStory_Handler,
		},
		{
			MethodName: "DeleteStory",
			Handler:    _StoryService_DeleteStory_Handler,
		},
		{
			MethodName: "GetStoriesFeed",
			Handler:    _StoryService_GetStoriesFeed_Handler,
		},
		{
			MethodName: "GetUserStories",
			Handler:    _StoryService_GetUserStories_Handler,
		},
		{
			MethodName: "RecordView",
			Handler:    _StoryService_RecordView_Handler,
		},
		{
			MethodName: "ReactToStory",
			Handler:    _StoryService_ReactToStory_Handler,
		},
		{
			MethodName: "GetStoryViewers",
			Handler:    _StoryService_GetStoryViewers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/story/v1/story.proto",
}
