// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/reel/v1/reel.proto

package reelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReelId        string                 `protobuf:"bytes,1,opt,name=reel_id,json=reelId,proto3" json:"reel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReelRequest) Reset() {
	*x = GetReelRequest{}
	mi := &file_proto_reel_v1_reel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReelRequest) ProtoMessage() {}

func (x *GetReelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reel_v1_reel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReelRequest.ProtoReflect.Descriptor instead.
func (*GetReelRequest) Descriptor() ([]byte, []int) {
	return file_proto_reel_v1_reel_proto_rawDescGZIP(), []int{0}
}

func (x *GetReelRequest) GetReelId() string {
	if x != nil {
		return x.ReelId
	}
	return ""
}

type GetReelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reel          *Reel                  `protobuf:"bytes,1,opt,name=reel,proto3" json:"reel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReelResponse) Reset() {
	*x = GetReelResponse{}
	mi := &file_proto_reel_v1_reel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReelResponse) ProtoMessage() {}

func (x *GetReelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reel_v1_reel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReelResponse.ProtoReflect.Descriptor instead.
func (*GetReelResponse) Descriptor() ([]byte, []int) {
	return file_proto_reel_v1_reel_proto_rawDescGZIP(), []int{1}
}

func (x *GetReelResponse) GetReel() *Reel {
	if x != nil {
		return x.Reel
	}
	return nil
}

type GetUserReelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReelsRequest) Reset() {
	*x = GetUserReelsRequest{}
	mi := &file_proto_reel_v1_reel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReelsRequest) ProtoMessage() {}

func (x *GetUserReelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reel_v1_reel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReelsRequest.ProtoReflect.Descriptor instead.
func (*GetUserReelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_reel_v1_reel_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserReelsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserReelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reels         []*Reel                `protobuf:"bytes,1,rep,name=reels,proto3" json:"reels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReelsResponse) Reset() {
	*x = GetUserReelsResponse{}
	mi := &file_proto_reel_v1_reel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReelsResponse) ProtoMessage() {}

func (x *GetUserReelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reel_v1_reel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReelsResponse.ProtoReflect.Descriptor instead.
func (*GetUserReelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_reel_v1_reel_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserReelsResponse) GetReels() []*Reel {
	if x != nil {
		return x.Reels
	}
	return nil
}

type GetReelsFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewerId      string                 `protobuf:"bytes,1,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReelsFeedRequest) Reset() {
	*x = GetReelsFeedRequest{}
	mi := &file_proto_reel_v1_reel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReelsFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReelsFeedRequest) ProtoMessage() {}

func (x *GetReelsFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reel_v1_reel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReelsFeedRequest.ProtoReflect.Descriptor instead.
func (*GetReelsFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_reel_v1_reel_proto_rawDescGZIP(), []int{4}
}

func (x *GetReelsFeedRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *GetReelsFeedRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetReelsFeedRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetReelsFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reels         []*Reel                `protobuf:"bytes,1,rep,name=reels,proto3" json:"reels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReelsFeedResponse) Reset() {
	*x = GetReelsFeedResponse{}
	mi := &file_proto_reel_v1_reel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReelsFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReelsFeedResponse) ProtoMessage() {}

func (x *GetReelsFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reel_v1_reel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReelsFeedResponse.ProtoReflect.Descriptor instead.
func (*GetReelsFeedResponse) Descriptor() ([]byte, []int) {
	return file_proto_reel_v1_reel_proto_rawDescGZIP(), []int{5}
}

func (x *GetReelsFeedResponse) GetReels() []*Reel {
	if x != nil {
		return x.Reels
	}
	return nil
}

type Reel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Caption       string                 `protobuf:"bytes,5,opt,name=caption,proto3" json:"caption,omitempty"`
	Duration      float64                `protobuf:"fixed64,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Privacy       string                 `protobuf:"bytes,7,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Views         int64                  `protobuf:"varint,8,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int64                  `protobuf:"varint,9,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments      int64                  `protobuf:"varint,10,opt,name=comments,proto3" json:"comments,omitempty"`
	Author        *Author                `protobuf:"bytes,11,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reel) Reset() {
	*x = Reel{}
	mi := &file_proto_reel_v1_reel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reel) ProtoMessage() {}

func (x *Reel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reel_v1_reel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reel.ProtoReflect.Descriptor instead.
func (*Reel) Descriptor() ([]byte, []int) {
	return file_proto_reel_v1_reel_proto_rawDescGZIP(), []int{6}
}

func (x *Reel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reel) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reel) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Reel) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Reel) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Reel) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Reel) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *Reel) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Reel) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Reel) GetComments() int64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *Reel) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Reel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Reel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_proto_reel_v1_reel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reel_v1_reel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_proto_reel_v1_reel_proto_rawDescGZIP(), []int{7}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Author) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Author) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_proto_reel_v1_reel_proto protoreflect.FileDescriptor

const file_proto_reel_v1_reel_proto_rawDesc = "" +
	"\n" +
	"\x18proto/reel/v1/reel.proto\x12\areel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\x0eGetReelRequest\x12\x17\n" +
	"\areel_id\x18\x01 \x01(\tR\x06reelId\"4\n" +
	"\x0fGetReelResponse\x12!\n" +
	"\x04reel\x18\x01 \x01(\v2\r.reel.v1.ReelR\x04reel\".\n" +
	"\x13GetUserReelsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x14GetUserReelsResponse\x12#\n" +
	"\x05reels\x18\x01 \x03(\v2\r.reel.v1.ReelR\x05reels\"`\n" +
	"\x13GetReelsFeedRequest\x12\x1b\n" +
	"\tviewer_id\x18\x01 \x01(\tR\bviewerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\";\n" +
	"\x14GetReelsFeedResponse\x12#\n" +
	"\x05reels\x18\x01 \x03(\v2\r.reel.v1.ReelR\x05reels\"\xa8\x03\n" +
	"\x04Reel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl\x12#\n" +
	"\rthumbnail_url\x18\x04 \x01(\tR\fthumbnailUrl\x12\x18\n" +
	"\acaption\x18\x05 \x01(\tR\acaption\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x01R\bduration\x12\x18\n" +
	"\aprivacy\x18\a \x01(\tR\aprivacy\x12\x14\n" +
	"\x05views\x18\b \x01(\x03R\x05views\x12\x14\n" +
	"\x05likes\x18\t \x01(\x03R\x05likes\x12\x1a\n" +
	"\bcomments\x18\n" +
	" \x01(\x03R\bcomments\x12'\n" +
	"\x06author\x18\v \x01(\v2\x0f.reel.v1.AuthorR\x06author\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"i\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName2\xe5\x01\n" +
	"\vReelService\x12<\n" +
	"\aGetReel\x12\x17.reel.v1.GetReelRequest\x1a\x18.reel.v1.GetReelResponse\x12K\n" +
	"\fGetUserReels\x12\x1c.reel.v1.GetUserReelsRequest\x1a\x1d.reel.v1.GetUserReelsResponse\x12K\n" +
	"\fGetReelsFeed\x12\x1c.reel.v1.GetReelsFeedRequest\x1a\x1d.reel.v1.GetReelsFeedResponseBHZFgithub.com/MuhibNayem/connectify-v2/shared-entity/proto/reel/v1;reelpbb\x06proto3"

var (
	file_proto_reel_v1_reel_proto_rawDescOnce sync.Once
	file_proto_reel_v1_reel_proto_rawDescData []byte
)

func file_proto_reel_v1_reel_proto_rawDescGZIP() []byte {
	file_proto_reel_v1_reel_proto_rawDescOnce.Do(func() {
		file_proto_reel_v1_reel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reel_v1_reel_proto_rawDesc), len(file_proto_reel_v1_reel_proto_rawDesc)))
	})
	return file_proto_reel_v1_reel_proto_rawDescData
}

var file_proto_reel_v1_reel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_reel_v1_reel_proto_goTypes = []any{
	(*GetReelRequest)(nil),        // 0: reel.v1.GetReelRequest
	(*GetReelResponse)(nil),       // 1: reel.v1.GetReelResponse
	(*GetUserReelsRequest)(nil),   // 2: reel.v1.GetUserReelsRequest
	(*GetUserReelsResponse)(nil),  // 3: reel.v1.GetUserReelsResponse
	(*GetReelsFeedRequest)(nil),   // 4: reel.v1.GetReelsFeedRequest
	(*GetReelsFeedResponse)(nil),  // 5: reel.v1.GetReelsFeedResponse
	(*Reel)(nil),                  // 6: reel.v1.Reel
	(*Author)(nil),                // 7: reel.v1.Author
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_reel_v1_reel_proto_depIdxs = []int32{
	6, // 0: reel.v1.GetReelResponse.reel:type_name -> reel.v1.Reel
	6, // 1: reel.v1.GetUserReelsResponse.reels:type_name -> reel.v1.Reel
	6, // 2: reel.v1.GetReelsFeedResponse.reels:type_name -> reel.v1.Reel
	7, // 3: reel.v1.Reel.author:type_name -> reel.v1.Author
	8, // 4: reel.v1.Reel.created_at:type_name -> google.protobuf.Timestamp
	8, // 5: reel.v1.Reel.updated_at:type_name -> google.protobuf.Timestamp
	0, // 6: reel.v1.ReelService.GetReel:input_type -> reel.v1.GetReelRequest
	2, // 7: reel.v1.ReelService.GetUserReels:input_type -> reel.v1.GetUserReelsRequest
	4, // 8: reel.v1.ReelService.GetReelsFeed:input_type -> reel.v1.GetReelsFeedRequest
	1, // 9: reel.v1.ReelService.GetReel:output_type -> reel.v1.GetReelResponse
	3, // 10: reel.v1.ReelService.GetUserReels:output_type -> reel.v1.GetUserReelsResponse
	5, // 11: reel.v1.ReelService.GetReelsFeed:output_type -> reel.v1.GetReelsFeedResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_reel_v1_reel_proto_init() }
func file_proto_reel_v1_reel_proto_init() {
	if File_proto_reel_v1_reel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reel_v1_reel_proto_rawDesc), len(file_proto_reel_v1_reel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reel_v1_reel_proto_goTypes,
		DependencyIndexes: file_proto_reel_v1_reel_proto_depIdxs,
		MessageInfos:      file_proto_reel_v1_reel_proto_msgTypes,
	}.Build()
	File_proto_reel_v1_reel_proto = out.File
	file_proto_reel_v1_reel_proto_goTypes = nil
	file_proto_reel_v1_reel_proto_depIdxs = nil
}
